# -*- coding: utf-8 -*-
from zope.schema.vocabulary import SimpleVocabulary, SimpleTerm
from ntpu.content import MessageFactory as _

ReviewConfirm = SimpleVocabulary(
    [SimpleTerm(value=None, title=_(u'Please select')),
     SimpleTerm(value=True, title=_(u'True')),
     SimpleTerm(value=False, title=_(u'False')),]
)

StateZh_TW = {
    'draft':u'草稿',
    'submitted':u'已提交',
    'accepted':u'建議推薦',
    'inReview':u'進入審查程序',
    'internalAssigned':u'已指定審查委員',
    'modifyThenReview':u'修改後再審',
    'reSubmitted':u'重新提交',
    'rejected':u'不予推薦',
    'retrial':u'再審',
}

Category = SimpleVocabulary(
    [SimpleTerm(value='E01', title=_(u'category_Education', default=u'Education')),
     SimpleTerm(value='E02', title=_(u'Humanities & Social Sciences')),
     SimpleTerm(value='S01', title=_(u'Humanity, Arts, and Dance')),
     SimpleTerm(value='S02', title=_(u'Sport Siology, Recreation and Leisure Studies')),
     SimpleTerm(value='S03', title=_(u'Sports Administration, Sports Management')),
     SimpleTerm(value='S04', title=_(u'Sport Pedagogy, Motor Behavior')),
     SimpleTerm(value='S05', title=_(u'Sport and Excercise Psychology')),
     SimpleTerm(value='S06', title=_(u'Coaching and Training')),
     SimpleTerm(value='S07', title=_(u'Sport Biomechancis')),
     SimpleTerm(value='S08', title=_(u'Exercise Physiology')),
     SimpleTerm(value='S09', title=_(u'Biochemistry of Exercise, Nutrition of Exercise')),
     SimpleTerm(value='S10', title=_(u'Sports Medicine')),
     SimpleTerm(value='S99', title=_(u'other')),]
)

BlindSetup = SimpleVocabulary(
    [SimpleTerm(value=True, title=_(u'Double-blind')),
     SimpleTerm(value=False, title=_(u'Single-blind'))]
)

AcceptOrReject = SimpleVocabulary(
    [SimpleTerm(value=None, title=_(u'Please select')),
     SimpleTerm(value='AR', title=_(u'Agreed to recommend')),
     SimpleTerm(value='AMAR', title=_(u'After the modification agreed to recommend')),
     SimpleTerm(value='MR', title=_(u'Modify and then review')),
     SimpleTerm(value='REJ', title=_(u'Reject')),]
)

Degree = SimpleVocabulary(
    [SimpleTerm(value=u"Bachelor's degree", title=_(u"Bachelor's degree")),
     SimpleTerm(value=u"Master's degree", title=_(u"Master's degree")),
     SimpleTerm(value=u'Doctor', title=_(u'Doctor')),
     SimpleTerm(value=u'Postdoc Research', title=_(u'Postdoc Research')),
     SimpleTerm(value=u'Other', title=_(u'Other')),]
)

GenderOption = SimpleVocabulary(
    [SimpleTerm(value=u'Male', title=_(u'Male')),
     SimpleTerm(value=u'Female', title=_(u'Female'))]
)

ArticleLanguage = SimpleVocabulary(
    [SimpleTerm(value=u"zh-tw", title=_(u"zh-tw")),
     SimpleTerm(value=u"zh-cn", title=_(u"zh-cn")),
     SimpleTerm(value=u"en-us", title=_(u"en-us")),]
)

ArticleType = SimpleVocabulary(
    [SimpleTerm(value=u"Original paper", title=_(u"Original paper")),
     SimpleTerm(value=u"Review article", title=_(u"Review article")),
     SimpleTerm(value=u"Research note", title=_(u"Research note")),]
)

CountryList = SimpleVocabulary(
    [SimpleTerm(value=u"Afghanistan", title=_(u"Afghanistan")),
     SimpleTerm(value=u"Albania", title=_(u"Albania")),
     SimpleTerm(value=u"Algeria", title=_(u"Algeria")),
     SimpleTerm(value=u"Andorra", title=_(u"Andorra")),
     SimpleTerm(value=u"Angola", title=_(u"Angola")),
     SimpleTerm(value=u"Antigua and Barbuda", title=_(u"Antigua and Barbuda")),
     SimpleTerm(value=u"Argentina", title=_(u"Argentina")),
     SimpleTerm(value=u"Armenia", title=_(u"Armenia")),
     SimpleTerm(value=u"Aruba", title=_(u"Aruba")),
     SimpleTerm(value=u"Australia", title=_(u"Australia")),
     SimpleTerm(value=u"Austria", title=_(u"Austria")),
     SimpleTerm(value=u"Azerbaijan", title=_(u"Azerbaijan")),
     SimpleTerm(value=u"Bahamas", title=_(u"Bahamas")),
     SimpleTerm(value=u"Bahrain", title=_(u"Bahrain")),
     SimpleTerm(value=u"Bangladesh", title=_(u"Bangladesh")),
     SimpleTerm(value=u"Barbados", title=_(u"Barbados")),
     SimpleTerm(value=u"Belarus", title=_(u"Belarus")),
     SimpleTerm(value=u"Belgium", title=_(u"Belgium")),
     SimpleTerm(value=u"Belize", title=_(u"Belize")),
     SimpleTerm(value=u"Benin", title=_(u"Benin")),
     SimpleTerm(value=u"Bhutan", title=_(u"Bhutan")),
     SimpleTerm(value=u"Bolivia", title=_(u"Bolivia")),
     SimpleTerm(value=u"Bosnia and Herzegovina", title=_(u"Bosnia and Herzegovina")),
     SimpleTerm(value=u"Botswana", title=_(u"Botswana")),
     SimpleTerm(value=u"Brazil", title=_(u"Brazil")),
     SimpleTerm(value=u"Brunei", title=_(u"Brunei")),
     SimpleTerm(value=u"Bulgaria", title=_(u"Bulgaria")),
     SimpleTerm(value=u"Burkina Faso", title=_(u"Burkina Faso")),
     SimpleTerm(value=u"Burma", title=_(u"Burma")),
     SimpleTerm(value=u"Burundi", title=_(u"Burundi")),
     SimpleTerm(value=u"Cambodia", title=_(u"Cambodia")),
     SimpleTerm(value=u"Cameroon", title=_(u"Cameroon")),
     SimpleTerm(value=u"Canada", title=_(u"Canada")),
     SimpleTerm(value=u"Cape Verde", title=_(u"Cape Verde")),
     SimpleTerm(value=u"Central African Republic", title=_(u"Central African Republic")),
     SimpleTerm(value=u"Chad", title=_(u"Chad")),
     SimpleTerm(value=u"Chile", title=_(u"Chile")),
     SimpleTerm(value=u"China", title=_(u"China")),
     SimpleTerm(value=u"Colombia", title=_(u"Colombia")),
     SimpleTerm(value=u"Comoros", title=_(u"Comoros")),
     SimpleTerm(value=u"Congo", title=_(u"Congo")),
     SimpleTerm(value=u"Costa Rica", title=_(u"Costa Rica")),
     SimpleTerm(value=u"Cote d'Ivoire", title=_(u"Cote d'Ivoire")),
     SimpleTerm(value=u"Croatia", title=_(u"Croatia")),
     SimpleTerm(value=u"Cuba", title=_(u"Cuba")),
     SimpleTerm(value=u"Curacao", title=_(u"Curacao")),
     SimpleTerm(value=u"Cyprus", title=_(u"Cyprus")),
     SimpleTerm(value=u"Czech Republic", title=_(u"Czech Republic")),
     SimpleTerm(value=u"Denmark", title=_(u"Denmark")),
     SimpleTerm(value=u"Djibouti", title=_(u"Djibouti")),
     SimpleTerm(value=u"Dominica", title=_(u"Dominica")),
     SimpleTerm(value=u"Dominican Republic", title=_(u"Dominican Republic")),
     SimpleTerm(value=u"East Timor", title=_(u"East Timor")),
     SimpleTerm(value=u"Ecuador", title=_(u"Ecuador")),
     SimpleTerm(value=u"Egypt", title=_(u"Egypt")),
     SimpleTerm(value=u"El Salvador", title=_(u"El Salvador")),
     SimpleTerm(value=u"Equatorial Guinea", title=_(u"Equatorial Guinea")),
     SimpleTerm(value=u"Eritrea", title=_(u"Eritrea")),
     SimpleTerm(value=u"Estonia", title=_(u"Estonia")),
     SimpleTerm(value=u"Ethiopia", title=_(u"Ethiopia")),
     SimpleTerm(value=u"Fiji", title=_(u"Fiji")),
     SimpleTerm(value=u"Finland", title=_(u"Finland")),
     SimpleTerm(value=u"France", title=_(u"France")),
     SimpleTerm(value=u"Gabon", title=_(u"Gabon")),
     SimpleTerm(value=u"Gambia", title=_(u"Gambia")),
     SimpleTerm(value=u"Georgia", title=_(u"Georgia")),
     SimpleTerm(value=u"Germany", title=_(u"Germany")),
     SimpleTerm(value=u"Ghana", title=_(u"Ghana")),
     SimpleTerm(value=u"Greece", title=_(u"Greece")),
     SimpleTerm(value=u"Grenada", title=_(u"Grenada")),
     SimpleTerm(value=u"Guatemala", title=_(u"Guatemala")),
     SimpleTerm(value=u"Guinea", title=_(u"Guinea")),
     SimpleTerm(value=u"Guinea-Bissau", title=_(u"Guinea-Bissau")),
     SimpleTerm(value=u"Guyana", title=_(u"Guyana")),
     SimpleTerm(value=u"Haiti", title=_(u"Haiti")),
     SimpleTerm(value=u"Holy See", title=_(u"Holy See")),
     SimpleTerm(value=u"Honduras", title=_(u"Honduras")),
     SimpleTerm(value=u"Hong Kong", title=_(u"Hong Kong")),
     SimpleTerm(value=u"Hungary", title=_(u"Hungary")),
     SimpleTerm(value=u"Iceland", title=_(u"Iceland")),
     SimpleTerm(value=u"India", title=_(u"India")),
     SimpleTerm(value=u"Indonesia", title=_(u"Indonesia")),
     SimpleTerm(value=u"Iran", title=_(u"Iran")),
     SimpleTerm(value=u"Iraq", title=_(u"Iraq")),
     SimpleTerm(value=u"Ireland", title=_(u"Ireland")),
     SimpleTerm(value=u"Israel", title=_(u"Israel")),
     SimpleTerm(value=u"Italy", title=_(u"Italy")),
     SimpleTerm(value=u"Jamaica", title=_(u"Jamaica")),
     SimpleTerm(value=u"Japan", title=_(u"Japan")),
     SimpleTerm(value=u"Jordan", title=_(u"Jordan")),
     SimpleTerm(value=u"Kazakhstan", title=_(u"Kazakhstan")),
     SimpleTerm(value=u"Kenya", title=_(u"Kenya")),
     SimpleTerm(value=u"Kiribati", title=_(u"Kiribati")),
     SimpleTerm(value=u"Korea, North", title=_(u"Korea, North")),
     SimpleTerm(value=u"Korea, South", title=_(u"Korea, South")),
     SimpleTerm(value=u"Kosovo", title=_(u"Kosovo")),
     SimpleTerm(value=u"Kuwait", title=_(u"Kuwait")),
     SimpleTerm(value=u"Kyrgyzstan", title=_(u"Kyrgyzstan")),
     SimpleTerm(value=u"Laos", title=_(u"Laos")),
     SimpleTerm(value=u"Latvia", title=_(u"Latvia")),
     SimpleTerm(value=u"Lebanon", title=_(u"Lebanon")),
     SimpleTerm(value=u"Lesotho", title=_(u"Lesotho")),
     SimpleTerm(value=u"Liberia", title=_(u"Liberia")),
     SimpleTerm(value=u"Libya", title=_(u"Libya")),
     SimpleTerm(value=u"Liechtenstein", title=_(u"Liechtenstein")),
     SimpleTerm(value=u"Lithuania", title=_(u"Lithuania")),
     SimpleTerm(value=u"Luxembourg", title=_(u"Luxembourg")),
     SimpleTerm(value=u"Macau", title=_(u"Macau")),
     SimpleTerm(value=u"Macedonia", title=_(u"Macedonia")),
     SimpleTerm(value=u"Madagascar", title=_(u"Madagascar")),
     SimpleTerm(value=u"Malawi", title=_(u"Malawi")),
     SimpleTerm(value=u"Malaysia", title=_(u"Malaysia")),
     SimpleTerm(value=u"Maldives", title=_(u"Maldives")),
     SimpleTerm(value=u"Mali", title=_(u"Mali")),
     SimpleTerm(value=u"Malta", title=_(u"Malta")),
     SimpleTerm(value=u"Marshall Islands", title=_(u"Marshall Islands")),
     SimpleTerm(value=u"Mauritania", title=_(u"Mauritania")),
     SimpleTerm(value=u"Mauritius", title=_(u"Mauritius")),
     SimpleTerm(value=u"Mexico", title=_(u"Mexico")),
     SimpleTerm(value=u"Micronesia", title=_(u"Micronesia")),
     SimpleTerm(value=u"Moldova", title=_(u"Moldova")),
     SimpleTerm(value=u"Monaco", title=_(u"Monaco")),
     SimpleTerm(value=u"Mongolia", title=_(u"Mongolia")),
     SimpleTerm(value=u"Montenegro", title=_(u"Montenegro")),
     SimpleTerm(value=u"Morocco", title=_(u"Morocco")),
     SimpleTerm(value=u"Mozambique", title=_(u"Mozambique")),
     SimpleTerm(value=u"Namibia", title=_(u"Namibia")),
     SimpleTerm(value=u"Nauru", title=_(u"Nauru")),
     SimpleTerm(value=u"Nepal", title=_(u"Nepal")),
     SimpleTerm(value=u"Netherlands", title=_(u"Netherlands")),
     SimpleTerm(value=u"Netherlands Antilles", title=_(u"Netherlands Antilles")),
     SimpleTerm(value=u"New Zealand", title=_(u"New Zealand")),
     SimpleTerm(value=u"Nicaragua", title=_(u"Nicaragua")),
     SimpleTerm(value=u"Niger", title=_(u"Niger")),
     SimpleTerm(value=u"Nigeria", title=_(u"Nigeria")),
     SimpleTerm(value=u"Norway", title=_(u"Norway")),
     SimpleTerm(value=u"Oman", title=_(u"Oman")),
     SimpleTerm(value=u"Pakistan", title=_(u"Pakistan")),
     SimpleTerm(value=u"Palau", title=_(u"Palau")),
     SimpleTerm(value=u"Palestinian Territories", title=_(u"Palestinian Territories")),
     SimpleTerm(value=u"Panama", title=_(u"Panama")),
     SimpleTerm(value=u"Papua New Guinea", title=_(u"Papua New Guinea")),
     SimpleTerm(value=u"Paraguay", title=_(u"Paraguay")),
     SimpleTerm(value=u"Peru", title=_(u"Peru")),
     SimpleTerm(value=u"Philippines", title=_(u"Philippines")),
     SimpleTerm(value=u"Poland", title=_(u"Poland")),
     SimpleTerm(value=u"Portugal", title=_(u"Portugal")),
     SimpleTerm(value=u"Qatar", title=_(u"Qatar")),
     SimpleTerm(value=u"Romania", title=_(u"Romania")),
     SimpleTerm(value=u"Russia", title=_(u"Russia")),
     SimpleTerm(value=u"Rwanda", title=_(u"Rwanda")),
     SimpleTerm(value=u"Saint Kitts and Nevis", title=_(u"Saint Kitts and Nevis")),
     SimpleTerm(value=u"Saint Lucia", title=_(u"Saint Lucia")),
     SimpleTerm(value=u"Saint Vincent and the Grenadines", title=_(u"Saint Vincent and the Grenadines")),
     SimpleTerm(value=u"Samoa", title=_(u"Samoa")),
     SimpleTerm(value=u"San Marino", title=_(u"San Marino")),
     SimpleTerm(value=u"Sao Tome and Principe", title=_(u"Sao Tome and Principe")),
     SimpleTerm(value=u"Saudi Arabia", title=_(u"Saudi Arabia")),
     SimpleTerm(value=u"Senegal", title=_(u"Senegal")),
     SimpleTerm(value=u"Serbia", title=_(u"Serbia")),
     SimpleTerm(value=u"Seychelles", title=_(u"Seychelles")),
     SimpleTerm(value=u"Sierra Leone", title=_(u"Sierra Leone")),
     SimpleTerm(value=u"Singapore", title=_(u"Singapore")),
     SimpleTerm(value=u"Sint Maarten", title=_(u"Sint Maarten")),
     SimpleTerm(value=u"Slovakia", title=_(u"Slovakia")),
     SimpleTerm(value=u"Slovenia", title=_(u"Slovenia")),
     SimpleTerm(value=u"Solomon Islands", title=_(u"Solomon Islands")),
     SimpleTerm(value=u"Somalia", title=_(u"Somalia")),
     SimpleTerm(value=u"South Africa", title=_(u"South Africa")),
     SimpleTerm(value=u"South Sudan", title=_(u"South Sudan")),
     SimpleTerm(value=u"Spain", title=_(u"Spain")),
     SimpleTerm(value=u"Sri Lanka", title=_(u"Sri Lanka")),
     SimpleTerm(value=u"Sudan", title=_(u"Sudan")),
     SimpleTerm(value=u"Suriname", title=_(u"Suriname")),
     SimpleTerm(value=u"Swaziland", title=_(u"Swaziland")),
     SimpleTerm(value=u"Sweden", title=_(u"Sweden")),
     SimpleTerm(value=u"Switzerland", title=_(u"Switzerland")),
     SimpleTerm(value=u"Syria", title=_(u"Syria")),
     SimpleTerm(value=u"Taiwan", title=_(u"Taiwan")),
     SimpleTerm(value=u"Tajikistan", title=_(u"Tajikistan")),
     SimpleTerm(value=u"Tanzania", title=_(u"Tanzania")),
     SimpleTerm(value=u"Thailand", title=_(u"Thailand")),
     SimpleTerm(value=u"Togo", title=_(u"Togo")),
     SimpleTerm(value=u"Tonga", title=_(u"Tonga")),
     SimpleTerm(value=u"Trinidad and Tobago", title=_(u"Trinidad and Tobago")),
     SimpleTerm(value=u"Tunisia", title=_(u"Tunisia")),
     SimpleTerm(value=u"Turkey", title=_(u"Turkey")),
     SimpleTerm(value=u"Turkmenistan", title=_(u"Turkmenistan")),
     SimpleTerm(value=u"Tuvalu", title=_(u"Tuvalu")),
     SimpleTerm(value=u"Uganda", title=_(u"Uganda")),
     SimpleTerm(value=u"Ukraine", title=_(u"Ukraine")),
     SimpleTerm(value=u"United Arab Emirates", title=_(u"United Arab Emirates")),
     SimpleTerm(value=u"United Kingdom", title=_(u"United Kingdom")),
     SimpleTerm(value=u"United States", title=_(u"United States")),
     SimpleTerm(value=u"Uruguay", title=_(u"Uruguay")),
     SimpleTerm(value=u"Uzbekistan", title=_(u"Uzbekistan")),
     SimpleTerm(value=u"Vanuatu", title=_(u"Vanuatu")),
     SimpleTerm(value=u"Venezuela", title=_(u"Venezuela")),
     SimpleTerm(value=u"Vietnam", title=_(u"Vietnam")),
     SimpleTerm(value=u"Yemen", title=_(u"Yemen")),
     SimpleTerm(value=u"Zambia", title=_(u"Zambia")),
     SimpleTerm(value=u"Zimbabwe", title=_(u"Zimbabwe")),]
)
